### ISSUE TITLE
method missing error

### ISSUE THREAD

**Issue by mfrederickson** [gokuu/jasper-command-line#1]
Why am I getting this, and how do I fix it?

```
jasper-command-line --jasper report2.jrxml --data-file sample.xml 
```

produces

```
Error: Error loading object from file : report2.jrxml
jasper.rb:82:in `method_missing' 
...
```

**Comment by mfrederickson** [comment]
I was able to resolve this by passing in the name of `report2.jasper` instead of `report2.jrxml` after making sure that the .jasper file existed.  I thought it would have produced it, but I guess not.

**Comment by gokuu** [comment]
Hi,

You're right in assuming that the `report2.jasper` file should be produced. The application doesn't, in fact, work correctly if you supply the `--jasper report2.jrxml`. You must supply `--jasper report2.jasper`, but it should rebuild the `report2.jasper` file from the `report2.jrxml` file if 1 of 2 cases occurs (assuming the `report2.jrxml` file exists):
- The `report2.jasper` doesn't exist
- The `report2.jasper` modification time is earlier than the `report2.jrxml` modification time

I'll have to fix the program to accept both `.jasper` and `.jrxml` files.
